inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7

  Exclude:
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'

Layout/LineLength:
  Exclude:
    - simulator.rb

Lint/UselessAssignment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false
